### ISSUE TITLE
Looking for Rocm enabled Alphafold image

### ISSUE THREAD

**Issue by mdondrup** [srinivamd/rocminstaller#5] opened 2023-01-06 10:14 UTC
Hi, 
I am looking for an Alphafold image that could run on the new [LUMI-G ](https://docs.lumi-supercomputer.eu/hardware/compute/lumig/) infrastructure and therefore supports rocm instead of cuda. I found a comment indicating you had created one, but I am not sure which one that is. Could you give me a hint towards the right repository?

Best regards
Michael

**Comment by srinivamd** [comment] 2023-01-06 11:22
@mdondrup The ROCm port docker image is a private docker: `amddcgpuce/rocmalphafold_22_tf29`. Could you send me an email with your request and I will check internally on how to share it - will need your docker hub handle.

Below is the docker run command for already built Alphafold container without the source codes:
```
$sudo docker run -it --ipc=host --device=/dev/kfd --device=/dev/dri -v ~:/datadisk-docker --group-add video --cap-add=SYS_PTRACE --security-opt seccomp=unconfined amddcgpuce/rocmalphafold_22_tf29
```
To run the alphafold test In the container use the below command:
```
$HHLIB=/opt/hhsuite python3 ./run_alphafold.py --use_gpu_relax --fasta_paths=/home/alphafold/input.monomer.fasta --uniref90_database_path=/datadisk-docker/ALPHAFOLD/uniref90/uniref90.fasta --mgnify_database_path=/datadisk-docker/ALPHAFOLD/mgnify/mgy_clusters_2018_12.fa --pdb70_database_path=/datadisk-docker/ALPHAFOLD/pdb70/pdb70 --data_dir=/datadisk-docker/ALPHAFOLD --template_mmcif_dir=/datadisk-docker/ALPHAFOLD/pdb_mmcif/mmcif_files --obsolete_pdbs_path=/datadisk-docker/ALPHAFOLD/pdb_mmcif/obsolete.dat --small_bfd_database_path=/datadisk-docker/ALPHAFOLD/small_bfd/bfd-first_non_consensus_sequences.fasta --output_dir=/datadisk-docker/Documents.alphafold/output --model_preset=monomer --max_template_date=2020-05-14 --db_preset=reduced_dbs --benchmark=False --logtostderr --hhsearch_binary_path=/opt/hhsuite/bin/hhsearch --hhblits_binary_path=/opt/hhsuite/bin/hhblits
```

To run the alphafold test directly from local machine with input `/home/alphafold/input/input.monomer.fasta` and alphafold database mounted volume in docker at  `/datadisk-docker/ALPHAFOLD` use the below command:
```
$sudo docker run -it --ipc=host --device=/dev/kfd --device=/dev/dri -v ~:/datadisk-docker --group-add video --cap-add=SYS_PTRACE --security-opt seccomp=unconfined -e HHLIB=/opt/hhsuite amddcgpuce/rocmalphafold_22_tf29 /bin/bash -c "cd /home/alphafold; python3 ./run_alphafold.py --use_gpu_relax --fasta_paths=/home/alphafold/input.monomer.fasta --uniref90_database_path=/datadisk-docker/ALPHAFOLD/uniref90/uniref90.fasta --mgnify_database_path=/datadisk-docker/ALPHAFOLD/mgnify/mgy_clusters_2018_12.fa --pdb70_database_path=/datadisk-docker/ALPHAFOLD/pdb70/pdb70 --data_dir=/datadisk-docker/ALPHAFOLD --template_mmcif_dir=/datadisk-docker/ALPHAFOLD/pdb_mmcif/mmcif_files --obsolete_pdbs_path=/datadisk-docker/ALPHAFOLD/pdb_mmcif/obsolete.dat --small_bfd_database_path=/datadisk-docker/ALPHAFOLD/small_bfd/bfd-first_non_consensus_sequences.fasta --output_dir=/datadisk-docker/Documents.alphafold/output --model_preset=monomer --max_template_date=2020-05-14 --db_preset=reduced_dbs --benchmark=False --logtostderr --hhsearch_binary_path=/opt/hhsuite/bin/hhsearch --hhblits_binary_path=/opt/hhsuite/bin/hhblits"
```

**Comment by mdondrup** [comment] 2023-01-06 12:32
@srinivamd My handle is the same as here. I would have to run it inside singularity but expect to 
get some support from LUMI staff in case of difficulties with that. 

Best
Michael

**Comment by srinivamd** [comment] 2023-01-06 13:05
@mdondrup Ok. Docker can be converted to singularity sif image and used. Will check and give you access.

**Comment by srinivamd** [comment] 2023-01-06 14:48
@mdondrup Can you try now?

**Comment by srinivamd** [comment] 2023-01-06 16:46
@peterdfields

**Comment by peterdfields** [comment] 2023-01-06 17:02
@srinivamd My docker handle is the same as here as well if you could share the container with me as well.

**Comment by mdondrup** [comment] 2023-01-06 17:03
Hi again,

I have had to try a few times because I ran out of space in my partition and have not been successful so far. I could 
download the image but failed during building the .sif file
 But now the image has disappeared, have you removed it again?

Michael

**Comment by srinivamd** [comment] 2023-01-06 17:21
Yes @mdondrup only one collab possible in my account. Go ahead.

**Comment by mdondrup** [comment] 2023-01-06 17:42
Thank you so much, running now.

**Comment by peterdfields** [comment] 2023-01-06 18:00
@srinivamd I was able to pull the docker image successfully. I'm not able to try running it right away but will be able to do so this evening. In the meantime feel free to revoke my access to the private image if it is needed by others. Thank you again for sharing the file.

**Comment by mdondrup** [comment] 2023-01-06 18:00
Unfortunately, I am still running out of memory after requesting 100GB of  RAM. I suspect this is caused because of /tmp residing in RAM or 
home directory or project directory running full. I have only 50GB of disk at the moment.

I will have to contact LUMI support for help. Would it be possible to share your Dockerfile?

Best regards
Michael


>  singularity pull --docker-login  rocmalphafold.sif docker://amddcgpuce/rocmalphafold_22_tf29:5.2.0-ub20

INFO:    Converting OCI blobs to SIF format
WARNING: 'nodev' mount option set on /tmp, it could be a source of failure during build process
INFO:    Starting build...
Getting image source signatures
Copying blob d7bfe07ed847 skipped: already exists
Copying blob e9d380f924bd skipped: already exists
Copying blob af80a684c83d skipped: already exists
Copying blob 3c8e05d056df skipped: already exists
Copying blob a823aef4e59f [--------------------------------------] 0.0b / 0.0b
Copying config 57845dfcff done
Writing manifest to image destination
Storing signatures
2023/01/06 19:43:33  info unpack layer: sha256:d7bfe07ed8476565a440c2113cc64d7c0409dba8ef761fb3ec019d7e6b5952df
2023/01/06 19:43:33  warn xattr{etc/gshadow} ignoring ENOTSUP on setxattr “user.rootlesscontainers"
[...]
2023/01/06 19:48:00  warn xattr{/tmp/build-temp-095359136/rootfs/usr/local/lib/python3.8} destination filesystem does not support xattrs, further warnings will be suppressed
INFO:    Creating SIF file...
FATAL:   While making image from oci registry: error fetching image to cache: while building SIF from layers: while creating squashfs: create command failed: exit status 1:
FATAL ERROR: Out of memory (cache_alloc)

**Comment by srinivamd** [comment] 2023-01-07 00:59
@mdondrup 
```
singularity pull --docker-login rocmalphafold_22_tf29.5.2.0_ub20.sif docker://amddcgpuce/rocmalphafold_22_tf29:5.2.0-ub20
Enter Docker Username: ********
Enter Docker Password: 
INFO:    Converting OCI blobs to SIF format
INFO:    Starting build...
Getting image source signatures
Copying blob a823aef4e59f done  
Copying blob e9d380f924bd done  
Copying blob af80a684c83d done  
...
2023/01/06 18:47:37  info unpack layer: sha256:af80a684c83d8feaa41a3fe7cb025502f562ffe75d4b9dd9bed3fe1a89d70ecb
2023/01/06 18:47:37  info unpack layer: sha256:3c8e05d056df82616abfd12bef72b5d84b80bd52fcc9ef5966e999aa5a5492d4
2023/01/06 18:47:37  info unpack layer: sha256:a823aef4e59f1e77a3ea0cd2716882dd7b8a820dccb44d7fecd0d329e54a9883
INFO:    Creating SIF file...
$ ls -l *sif
-rwxrwxr-x 1 XXX XXX 5744209920 Jan  6 18:50 rocmalphafold_22_tf29.5.2.0_ub20.sif
```

**Comment by srinivamd** [comment] 2023-01-07 20:16
@mdondrup Please try this new image, `amddcgpuce/alphafold23:tf29-rocm540` (fixed image tag typo) Alphafold 2.3 (latest), OpenMM 77 and with ROCm 5.4.0. 
```
sudo docker run -it --ipc=host --device=/dev/kfd --device=/dev/dri -v ~:/datadisk-docker --group-add video --cap-add=SYS_PTRACE --security-opt seccomp=unconfined amddcgpuce/alphafold23:tf29-rocm540 /bin/bash
```
Example command from docker prompt to run `/home/alphafold/input.monomer.fasta` as input `monomer` with Alphafold database `ALPHAFOLD_DBS` mounted and accessible as `/datadisk-docker/ALPHAFOLD_DBS` inside docker. Please change the `output_dir` to a mount point outside the docker.
```
cd /home/alphafold

HHLIB=/opt/hhsuite python3 ./run_alphafold.py --use_gpu_relax --fasta_paths=/home/alphafold/input.monomer.fasta --uniref90_database_path=/datadisk-docker/ALPHAFOLD/uniref90/uniref90.fasta --mgnify_database_path=/datadisk-docker/ALPHAFOLD/mgnify/mgy_clusters_2018_12.fa --pdb70_database_path=/datadisk-docker/ALPHAFOLD/pdb70/pdb70 --data_dir=/datadisk-docker/ALPHAFOLD --template_mmcif_dir=/datadisk-docker/ALPHAFOLD/pdb_mmcif/mmcif_files --obsolete_pdbs_path=/datadisk-docker/ALPHAFOLD/pdb_mmcif/obsolete.dat --small_bfd_database_path=/datadisk-docker/ALPHAFOLD/small_bfd/bfd-first_non_consensus_sequences.fasta --output_dir=/ --model_preset=monomer --max_template_date=2020-05-14 --db_preset=reduced_dbs --benchmark=False --logtostderr --hhsearch_binary_path=/opt/hhsuite/bin/hhsearch --hhblits_binary_path=/opt/hhsuite/bin/hhblits
```
Example Singularity pull command
```
singularity pull --docker-login alphafold23_tf29_rocm540.sif docker://amddcgpuce/alphafold23:tf29-rocm540
```
@danny305
@peterdfields

**Comment by danny305** [comment] 2023-01-07 21:17
Here is my script I use to run alphafold on AMD hardware.
Update the docker image version according to your ROCM version:

```bash
#/bin/bash

fasta_file=$1
fasta_dir=$(dirname $fasta_file)
fasta_file=$(basename $fasta_file)
out_dir_default=$(dirname $PWD)
out_dir=${2:-$out_dir_default}

echo $fasta_dir
echo "Running $fasta_file through alphafold"
echo "Outputting structures to $out_dir"


docker run -it --ipc=host --device=/dev/kfd --device=/dev/dri --group-add video --cap-add=SYS_PTRACE --security-opt seccomp=unconfined \
-v /stor/scratch/AlphaFold/data.2:/datadisk-docker/ALPHAFOLD  \
-v $fasta_dir:/datadisk-docker/fasta \
-v $out_dir:/datadisk-docker/output \
-e HHLIB=/opt/hhsuite \
amddcgpuce/rocmalphafold_22_tf29:5.2.0-ub20 \
/bin/bash -c "
    cd /home/alphafold; \
    python3 ./run_alphafold.py \
        --fasta_paths=/datadisk-docker/fasta/$fasta_file \
        --output_dir=/datadisk-docker/output \
        --use_gpu_relax \
        --uniref90_database_path=/datadisk-docker/ALPHAFOLD/uniref90/uniref90.fasta \
        --mgnify_database_path=/datadisk-docker/ALPHAFOLD/mgnify/mgy_clusters_2018_12.fa \
        --pdb70_database_path=/datadisk-docker/ALPHAFOLD/pdb70/pdb70 \
        --data_dir=/datadisk-docker/ALPHAFOLD \
        --template_mmcif_dir=/datadisk-docker/ALPHAFOLD/pdb_mmcif/mmcif_files \
        --obsolete_pdbs_path=/datadisk-docker/ALPHAFOLD/pdb_mmcif/obsolete.dat \
        --small_bfd_database_path=/datadisk-docker/ALPHAFOLD/small_bfd/bfd-first_non_consensus_sequences.fasta \
        --model_preset=monomer \
        --max_template_date=2020-05-14 \
        --db_preset=reduced_dbs \
        --benchmark=False \
        --logtostderr \
        --hhsearch_binary_path=/opt/hhsuite/bin/hhsearch \
        --hhblits_binary_path=/opt/hhsuite/bin/hhblits \
"
```

**Comment by srinivamd** [comment] 2023-01-07 21:59
Thanks @danny305 Could you give the new alphafold23 docker image `amddcgpuce/alphafold23:tf29-rocm540` a test run? 

@mdondrup  Sample singulartiy command to run the monomer test shown earlier with docker, the alphafold DBS under `/home/master/ALPHAFOLD`:
```
singularity run --env HHLIB=/opt/hhsuite alphafold23_tf29_rocm540.sif python3 /home/alphafold/run_alphafold.py --use_gpu_relax --fasta_paths=/home/alphafold/input.monomer.fasta --uniref90_database_path=/home/master/ALPHAFOLD/uniref90/uniref90.fasta --mgnify_database_path=/home/master/ALPHAFOLD/mgnify/mgy_clusters_2018_12.fa --pdb70_database_path=/home/master/ALPHAFOLD/pdb70/pdb70 --data_dir=/home/master/ALPHAFOLD --template_mmcif_dir=/home/master/ALPHAFOLD/pdb_mmcif/mmcif_files --obsolete_pdbs_path=/home/master/ALPHAFOLD/pdb_mmcif/obsolete.dat --small_bfd_database_path=/home/master/ALPHAFOLD/small_bfd/bfd-first_non_consensus_sequences.fasta --output_dir=`pwd` --model_preset=monomer --max_template_date=2020-05-14 --db_preset=reduced_dbs --benchmark=False --logtostderr --hhsearch_binary_path=/opt/hhsuite/bin/hhsearch --hhblits_binary_path=/opt/hhsuite/bin/hhblits
```

**Comment by mdondrup** [comment] 2023-01-07 23:18
Thank you very much. I could pull the image in singularity and create the sif file:

-rwxrwx--- 1 xxx xxx 5505003520 Jan  8 00:45 alphafold23_tf29_rocm540.sif

I will give the test run a try once I have downloaded the sequence databases, possibly sometime next week.

Best regards

**Comment by peterdfields** [comment] 2023-01-07 23:43
@danny305 You script is missing a " at the very end, it should be the following I think:
```
#/bin/bash

fasta_file=$1
fasta_dir=$(dirname $fasta_file)
fasta_file=$(basename $fasta_file)
out_dir_default=$(dirname $PWD)
out_dir=${2:-$out_dir_default}

echo $fasta_dir
echo "Running $fasta_file through alphafold"
echo "Outputting structures to $out_dir"


docker run -it --ipc=host --device=/dev/kfd --device=/dev/dri --group-add video --cap-add=SYS_PTRACE --security-opt seccomp=unconfined \
-v /stor/scratch/AlphaFold/data.2:/datadisk-docker/ALPHAFOLD  \
-v $fasta_dir:/datadisk-docker/fasta \
-v $out_dir:/datadisk-docker/output \
-e HHLIB=/opt/hhsuite \
amddcgpuce/rocmalphafold_22_tf29:5.2.0-ub20 \
/bin/bash -c "
    cd /home/alphafold; \
    python3 ./run_alphafold.py \
        --fasta_paths=/datadisk-docker/fasta/$fasta_file \
        --output_dir=/datadisk-docker/output \
        --use_gpu_relax \
        --uniref90_database_path=/datadisk-docker/ALPHAFOLD/uniref90/uniref90.fasta \
        --mgnify_database_path=/datadisk-docker/ALPHAFOLD/mgnify/mgy_clusters_2018_12.fa \
        --pdb70_database_path=/datadisk-docker/ALPHAFOLD/pdb70/pdb70 \
        --data_dir=/datadisk-docker/ALPHAFOLD \
        --template_mmcif_dir=/datadisk-docker/ALPHAFOLD/pdb_mmcif/mmcif_files \
        --obsolete_pdbs_path=/datadisk-docker/ALPHAFOLD/pdb_mmcif/obsolete.dat \
        --small_bfd_database_path=/datadisk-docker/ALPHAFOLD/small_bfd/bfd-first_non_consensus_sequences.fasta \
        --model_preset=monomer \
        --max_template_date=2020-05-14 \
        --db_preset=reduced_dbs \
        --benchmark=False \
        --logtostderr \
        --hhsearch_binary_path=/opt/hhsuite/bin/hhsearch \
        --hhblits_binary_path=/opt/hhsuite/bin/hhblits \
"
```

**Comment by srinivamd** [comment] 2023-01-08 01:42
Closing this issue - please note that it is a prototype.

**Closed as completed by srinivamd** 2023-01-08 01:42 UTC

**Comment by mdondrup** [comment] 2023-01-26 09:19
Hi,
I just wanted to let you know that I am attempting to build my own rocm-enabled singularity version of alphafold here: 
https://github.com/mdondrup/alphafold/

The only addition is a singularity.def file. I am currently trying to build openmm from source as I think I cannot use conda to install it. That 'almost' works. Jax and Haiku seem to work too. I haven't managed to test alphafold yet. Any comments are welcome.

To build: `singularity build --remote --sandbox alphafold_rocm5.0.0 alphafold/singularity.def`

**Comment by srinivamd** [comment] 2023-02-17 03:06
@peterdfields @danny305 @mdondrup 
New alphafold23 docker `amddcgpuce/alphafold23:tf2.11-py39-rocm5.4.3` if you want to try. with `openmm 8.0`.

**Comment by peterdfields** [comment] 2023-02-17 03:25
@srinivamd sure, but it looks like access to the image isn't presently available publicly or for my account specifically. Can you share it with my account as you did before?

**Comment by srinivamd** [comment] 2023-02-17 03:31
@peterdfields please try now

**Comment by peterdfields** [comment] 2023-02-17 03:44
@srinivamd I was able to pull the image successfully, thank you. You can remove my access so that you can share the image with others. I will give it a try tomorrow and let you know if it works on my hardware.

**Comment by srinivamd** [comment] 2023-02-17 03:44
thanks @peterdfields

**Comment by danny305** [comment] 2023-02-17 18:03
@srinivamd I am trying to pull but I get request denied?

**Comment by srinivamd** [comment] 2023-02-18 23:54
@danny305 could you please try now

**Comment by danny305** [comment] 2023-02-19 17:25
Just tried it and it seems to be working. 

However, they just updated the rocm version on the UT servers and it is unable to find the GPUs so it's running the model on the CPUs. 

I'll update again later this week once Anna and the teams resolves what is going on with the GPUs. 

Thanks for the updated docker image!

**Comment by srinivamd** [comment] 2023-02-19 17:46
> it is unable to find the GPUs so it's running the model on the CPUs.

Looking into it @danny305 Thanks.

**Comment by peterdfields** [comment] 2023-02-20 01:02
@srinivamd I can confirm that this new image works on a machine with a AMD 6900XT (gfx1030) gpu on a quick protein example. Thanks @srinivamd for creating this image!

**Comment by srinivamd** [comment] 2023-02-20 05:29
@danny305 Could you try setting `JAX_PLATFORMS='rocm,cpu'` -- do you see GPU used?

**Comment by srinivamd** [comment] 2023-02-20 05:31
> @srinivamd I can confirm that this new image works on a machine with a AMD 6900XT (gfx1030) gpu on a quick protein example. Thanks @srinivamd for creating this image!

Thank you for the update @peterdfields
Is the GPU being utilized?

**Comment by mdondrup** [comment] 2023-02-20 08:48
Hi,
Thanks for this. could you let me pull the image too, please?

Michael

**Comment by srinivamd** [comment] 2023-02-20 14:00
@mdondrup could you please try now?

**Comment by peterdfields** [comment] 2023-02-21 15:25
> > @srinivamd I can confirm that this new image works on a machine with a AMD 6900XT (gfx1030) gpu on a quick protein example. Thanks @srinivamd for creating this image!
> 
> Thank you for the update @peterdfields Is the GPU being utilized?

@srinivamd I believe so. Is there are preferred way for tracking GPU vs. CPU utilization for the run?

**Comment by YumengYan** [comment] 2023-02-23 15:01
@srinivamd  Could you share the image with me? My docker handle is yym2mm. Thanks!
